// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsjgmwcbmqgldlsivgas.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indzamdtd2NibXFnbGRsc2l2Z2FzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzMDkyMTMsImV4cCI6MjA1Nzg4NTIxM30.6yPkdL2h0tLSj0cKfTQw_kVbwTMY32CMcr7MtS7ky08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);